services:
  nyapa-landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyapa-landing-page
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
